import crypto from 'node:crypto';
import { extractDomainInfo } from '../utils/domainChecker.js';

/**
 * Defang a URL to prevent accidental clicks or triggering web gateway filters
 * Example: https://evil.com/login -> hxxps[://]evil[.]com/login
 */
export function defangUrl(url) {
  if (!url || typeof url !== 'string') return '';
  return url
    .replace(/^http:\/\//i, 'hxxp[://]')
    .replace(/^https:\/\//i, 'hxxps[://]')
    .replace(/\.([a-zA-Z0-9_-]+)/g, '[.]$1');
}

/**
 * Defang an IP address (e.g. 192.168.1.1 -> 192[.]168[.]1[.]1)
 */
export function defangIp(ip) {
  if (!ip || typeof ip !== 'string') return '';
  return ip.replace(/\./g, '[.]');
}

/**
 * Extract structured Indicators of Compromise (IOCs) from email scan data
 */
export function extractIOCs(parsedEmail = {}, scanResult = {}) {
  const metadata = parsedEmail.metadata || scanResult.metadata || {};
  const heuristics = parsedEmail.heuristics || scanResult.heuristics || {};
  const securityHeaders = parsedEmail.securityHeaders || scanResult.security_headers || {};

  // 1. Calculate SHA-256 of subject + sender + body text
  const payloadToHash = `${metadata.from || ''}\n${metadata.subject || ''}\n${parsedEmail.content?.textBody || scanResult.explanation || ''}`;
  const sha256 = crypto.createHash('sha256').update(payloadToHash, 'utf-8').digest('hex');

  // 2. Extract sender domain
  const senderStr = metadata.from || '';
  const senderEmailMatch = senderStr.match(/<([^>]+)>/) || senderStr.match(/([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})/);
  const senderEmail = senderEmailMatch ? senderEmailMatch[1] : senderStr;
  const senderDomain = senderEmail.includes('@') ? senderEmail.split('@')[1].toLowerCase() : null;

  // 3. Extract sender IP from security headers if available
  const senderIpMatch = (securityHeaders.authResults || securityHeaders.returnPath || '')
    .match(/\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/);
  const senderIp = senderIpMatch ? senderIpMatch[0] : null;

  // 4. Extract domains and links from heuristics
  const observedDomains = new Set();
  const rawUrls = [];
  const defangedUrls = [];

  const links = heuristics.analyzedLinks || [];
  for (const l of links) {
    if (l.href) {
      rawUrls.push(l.href);
      defangedUrls.push(defangUrl(l.href));
    }
    if (l.domain) {
      observedDomains.add(l.domain.toLowerCase());
    }
  }

  // Also include sender domain
  if (senderDomain) {
    observedDomains.add(senderDomain);
  }

  // Lookalike targets
  const lookalikes = [];
  if (heuristics.flaggedIndicators) {
    for (const ind of heuristics.flaggedIndicators) {
      if (ind.type === 'lookalike_domain' || ind.indicator_type === 'lookalike_domain') {
        lookalikes.push(ind.detail);
      }
    }
  }

  return {
    emailSha256: sha256,
    subject: metadata.subject || '(No Subject)',
    sender: senderStr,
    senderEmail,
    senderDomain,
    defangedSenderDomain: senderDomain ? defangUrl(senderDomain) : 'N/A',
    senderIp: senderIp ? defangIp(senderIp) : 'Not extracted in headers',
    securityHeaders: {
      spf: securityHeaders.spf || 'unknown',
      dkim: securityHeaders.dkim || 'unknown',
      dmarc: securityHeaders.dmarc || 'unknown'
    },
    domains: Array.from(observedDomains),
    defangedDomains: Array.from(observedDomains).map(d => defangUrl(d)),
    rawUrls,
    defangedUrls,
    lookalikes,
    riskScore: scanResult.risk_score || 0,
    verdict: scanResult.verdict || 'UNKNOWN'
  };
}

/**
 * Generate a formal, standardized SOC Incident Ticket in Markdown
 */
export function generateSocTicketMarkdown(iocs, scanResult = {}) {
  const timestamp = new Date().toISOString();
  const verdict = (scanResult.verdict || iocs.verdict || 'UNKNOWN').toUpperCase();
  const riskScore = scanResult.risk_score ?? iocs.riskScore ?? 0;
  const tactics = (scanResult.tactics_detected || []).join(', ') || 'Social engineering, credential harvest';

  return `# [SEC-INCIDENT] Inbound Phishing Threat Triage Report
**Generated by PhishGuard Defense System**
*Report Date:* ${timestamp}
*Verdict:* **${verdict}** (Risk Score: **${riskScore}/100**)

---

## 1. Executive Summary
PhishGuard automated inspection triaged an inbound communication exhibiting high confidence indicators of a social engineering attack.
- **Target Organization Vector:** Email Credential Harvesting & Brand Impersonation
- **Primary Tactics Identified:** ${tactics}
- **AI Triage Explanation:** ${scanResult.explanation || 'Suspicious heuristics detected.'}

---

## 2. Technical Indicators of Compromise (IOCs)
> *Notice: All external destinations are strictly defanged according to RFC/CERT guidelines to prevent accidental interaction.*

| Indicator Type | Defanged Value | Status / Notes |
| :--- | :--- | :--- |
| **Email Payload SHA-256** | \`${iocs.emailSha256}\` | Unique threat signature |
| **Claimed Sender** | \`${iocs.sender}\` | Visible From header |
| **Sender Domain** | \`${iocs.defangedSenderDomain}\` | Authenticated sending domain |
| **Sender IP (Observed)** | \`${iocs.senderIp}\` | Mail transfer agent IP |
| **SPF Header** | \`${iocs.securityHeaders.spf.toUpperCase()}\` | Mail policy check |
| **DKIM Header** | \`${iocs.securityHeaders.dkim.toUpperCase()}\` | Cryptographic signature |
| **DMARC Header** | \`${iocs.securityHeaders.dmarc.toUpperCase()}\` | Domain alignment check |

### Defanged Malicious / Suspicious URLs
${iocs.defangedUrls.length > 0 
  ? iocs.defangedUrls.map(u => `- \`${u}\``).join('\n') 
  : '_No external links detected in message body._'}

### Targeted Brand Impersonations
${iocs.lookalikes.length > 0 
  ? iocs.lookalikes.map(l => `- ⚠️ ${l}`).join('\n') 
  : '_No explicit lookalike domain spoofing detected._'}

---

## 3. Recommended SOC Mitigation & Remediation Playbook
1. **Network Containment:** Block the observed sender domain and URLs at the perimeter firewall / Secure Web Gateway (SWG).
2. **Mail Gateway Rule:** Purge all emails containing SHA-256 \`${iocs.emailSha256}\` from enterprise mailboxes.
3. **Identity & Access Management:** Audit user directory for any employees who opened links to \`${iocs.defangedSenderDomain}\` in the last 24 hours; enforce password reset and revoke active SSO sessions if visited.
4. **Broadcast Alert:** Dispatch the sanitized internal warning message to department leads.
`;
}

/**
 * Generate multi-format DNS and Firewall blocklist rules
 */
export function generateBlocklistRules(iocs) {
  const domains = iocs.domains || [];

  // 1. Hosts file & Pi-hole format
  const hostsFormat = domains.map(d => `0.0.0.0 ${d}`).join('\n');

  // 2. Cloudflare Zero Trust / DNS Gateway CSV format
  const cloudflareCsv = ['Domain,Action,Reason']
    .concat(domains.map(d => `"${d}","BLOCK","PhishGuard Triage: Threat Score ${iocs.riskScore}"`))
    .join('\n');

  // 3. Raw domain list
  const rawList = domains.join('\n');

  return {
    hostsFormat: hostsFormat || '# No malicious domains detected to block',
    cloudflareCsv: cloudflareCsv || 'Domain,Action,Reason',
    rawList: rawList || '# No domains'
  };
}

/**
 * Generate a safe, pre-formatted warning notification for Slack/Teams/Email
 */
export function generateTeamWarningAlert(iocs, scanResult = {}) {
  const subject = iocs.subject || 'Suspicious Email';
  const claimedFrom = iocs.sender || 'Unknown Sender';
  const verdict = (scanResult.verdict || iocs.verdict || 'SUSPICIOUS').toUpperCase();

  return `🚨 *SECURITY ALERT: Suspicious Email Reported* 🚨

*Team Notice - Please Do Not Click or Reply*
A phishing email was detected by our security scanner and may be targeting team members.

• *Subject:* "${subject}"
• *Claimed From:* ${claimedFrom}
• *Threat Rating:* *${verdict}* (Risk Score: ${iocs.riskScore}/100)
• *Observed Impersonation / Hook:* ${scanResult.safe_summary || 'Urgent request for credentials or verification'}

*What You Should Do:*
1. If you received this email, *do not click any links or download attachments*.
2. Do not reply or send credentials.
3. Forward the email as an attachment to your IT/Security team and delete it.

_Stay safe and verify unexpected communications!_`;
}
